import assert from "node:assert/strict";
import { test } from "node:test";

import {
  InvalidStoredImportedArchiveRecordError,
  InvalidStoredLocalGameSaveRecordError,
  assertStoredImportedArchiveRecord,
  assertStoredLocalGameSaveRecord,
  clearLocalGameSaveRecord,
  createStoredImportedArchiveRecord,
  createStoredLocalGameSaveRecord,
  currentImportedArchiveKey,
  currentLocalGameSaveKey,
  saveImportedArchiveRecord,
  clearImportedArchiveRecord,
  saveLocalGameSaveRecord,
} from "@serfbound/app";
import { parseDosPaCatalog } from "@serfbound/assets";
import { startSerfboundLocalGame } from "@serfbound/engine";

class MemoryImportedArchiveStore {
  record = null;

  async loadCurrent() {
    return this.record === null
      ? null
      : {
          ...this.record,
          bytes: this.record.bytes.slice(0),
        };
  }

  async saveCurrent(record) {
    this.record = {
      ...record,
      bytes: record.bytes.slice(0),
    };
  }

  async clearCurrent() {
    this.record = null;
  }
}

class MemoryLocalGameSaveStore {
  record = null;

  async loadCurrent() {
    return this.record === null
      ? null
      : {
          ...this.record,
          dataSource: { ...this.record.dataSource },
          snapshot: {
            ...this.record.snapshot,
            data: { ...this.record.snapshot.data },
            settings: { ...this.record.snapshot.settings },
            state: {
              ...this.record.snapshot.state,
              map: { ...this.record.snapshot.state.map },
              clock: { ...this.record.snapshot.state.clock },
              random: {
                ...this.record.snapshot.state.random,
                state: [...this.record.snapshot.state.random.state],
              },
              counters: { ...this.record.snapshot.state.counters },
              builtStructures: this.record.snapshot.state.builtStructures.map((structure) => ({
                ...structure,
                tile: { ...structure.tile },
              })),
            },
            renderer: { ...this.record.snapshot.renderer },
          },
        };
  }

  async saveCurrent(record) {
    this.record = {
      ...record,
      dataSource: { ...record.dataSource },
      snapshot: {
        ...record.snapshot,
        data: { ...record.snapshot.data },
        settings: { ...record.snapshot.settings },
        state: {
          ...record.snapshot.state,
          map: { ...record.snapshot.state.map },
          clock: { ...record.snapshot.state.clock },
          random: {
            ...record.snapshot.state.random,
            state: [...record.snapshot.state.random.state],
          },
          counters: { ...record.snapshot.state.counters },
          builtStructures: record.snapshot.state.builtStructures.map((structure) => ({
            ...structure,
            tile: { ...structure.tile },
          })),
        },
        renderer: { ...record.snapshot.renderer },
      },
    };
  }

  async clearCurrent() {
    this.record = null;
  }
}

function createGeneratedPaArchive() {
  const bytes = new Uint8Array(24);
  const view = new DataView(bytes.buffer);
  view.setUint32(0, bytes.byteLength, true);
  view.setUint32(4, 1, true);
  view.setUint32(8, 8, true);
  view.setUint32(12, 16, true);
  return bytes;
}

function createStartedLocalGameSnapshot() {
  const result = startSerfboundLocalGame({
    data: {
      kind: "imported-dos-pa-catalog",
      archiveName: "SPAU.PA",
      byteLength: 32,
      entryCount: 2,
      definedArchiveEntries: 2,
      fixupCount: 0,
    },
  });
  assert.equal(result.status, "started");
  result.game.state.buildFlag({ column: 27, row: 21, position: 1371 });
  return result.game.snapshot();
}

test("imported archive records preserve metadata and clone generated bytes", () => {
  const sourceBytes = createGeneratedPaArchive();
  const record = createStoredImportedArchiveRecord({
    fileName: "SPAU.PA",
    normalizedName: "SPAU.PA",
    bytes: sourceBytes,
    importedAtIso: "2026-06-09T23:00:00.000Z",
  });

  sourceBytes.fill(0);

  assert.equal(record.schemaVersion, 1);
  assert.equal(record.storageKey, currentImportedArchiveKey);
  assert.equal(record.source, "dos-pa");
  assert.equal(record.fileName, "SPAU.PA");
  assert.equal(record.byteLength, 24);
  assert.equal(record.importedAtIso, "2026-06-09T23:00:00.000Z");
  assert.equal(parseDosPaCatalog(record.bytes).header.entryCount, 1);
});

test("imported archive store contract supports save, load, and clear", async () => {
  const store = new MemoryImportedArchiveStore();
  const record = createStoredImportedArchiveRecord({
    fileName: "SPAU.PA",
    normalizedName: "SPAU.PA",
    bytes: createGeneratedPaArchive(),
    importedAtIso: "2026-06-09T23:00:00.000Z",
  });

  assert.equal(await store.loadCurrent(), null);
  assert.deepEqual(await saveImportedArchiveRecord(store, record), {
    state: "persisted",
  });

  const loaded = await store.loadCurrent();
  assert.notEqual(loaded, null);
  assert.deepEqual(
    {
      ...loaded,
      bytes: Array.from(new Uint8Array(loaded.bytes)),
    },
    {
      ...record,
      bytes: Array.from(new Uint8Array(record.bytes)),
    },
  );

  assert.deepEqual(await clearImportedArchiveRecord(store), {
    state: "cleared",
  });
  assert.equal(await store.loadCurrent(), null);
});

test("imported archive records reject corrupt metadata and storage version mismatches", () => {
  const record = createStoredImportedArchiveRecord({
    fileName: "SPAU.PA",
    normalizedName: "SPAU.PA",
    bytes: createGeneratedPaArchive(),
    importedAtIso: "2026-06-09T23:00:00.000Z",
  });

  assert.equal(assertStoredImportedArchiveRecord(record), record);
  assert.throws(
    () => assertStoredImportedArchiveRecord({ ...record, schemaVersion: 2 }),
    InvalidStoredImportedArchiveRecordError,
  );
  assert.throws(
    () => assertStoredImportedArchiveRecord({ ...record, byteLength: 999 }),
    InvalidStoredImportedArchiveRecordError,
  );
});

test("storage operation helpers return recoverable error states", async () => {
  const failingStore = {
    async loadCurrent() {
      return null;
    },
    async saveCurrent() {
      throw new Error("quota exhausted");
    },
    async clearCurrent() {
      throw new Error("delete denied");
    },
  };
  const record = createStoredImportedArchiveRecord({
    fileName: "SPAU.PA",
    normalizedName: "SPAU.PA",
    bytes: createGeneratedPaArchive(),
  });

  assert.deepEqual(await saveImportedArchiveRecord(failingStore, record), {
    state: "error",
    message: "quota exhausted",
  });
  assert.deepEqual(await clearImportedArchiveRecord(failingStore), {
    state: "error",
    message: "delete denied",
  });
});

test("local game save records preserve versioned source metadata and snapshots", () => {
  const snapshot = createStartedLocalGameSnapshot();
  const record = createStoredLocalGameSaveRecord({
    snapshot,
    savedAtIso: "2026-06-09T23:30:00.000Z",
  });

  snapshot.state.builtStructures[0].tile.column = 0;

  assert.equal(record.schemaVersion, 1);
  assert.equal(record.storageKey, currentLocalGameSaveKey);
  assert.equal(record.source, "serfbound-local-game");
  assert.equal(record.savedAtIso, "2026-06-09T23:30:00.000Z");
  assert.deepEqual(record.dataSource, {
    kind: "imported-dos-pa-catalog",
    archiveName: "SPAU.PA",
    byteLength: 32,
    entryCount: 2,
    definedArchiveEntries: 2,
    fixupCount: 0,
  });
  assert.deepEqual(record.snapshot.state.builtStructures, [
    {
      id: 1,
      kind: "flag",
      placedAtTick: 0,
      tile: { column: 27, row: 21, position: 1371 },
    },
  ]);
});

test("local game save store contract supports save, load, and clear", async () => {
  const store = new MemoryLocalGameSaveStore();
  const record = createStoredLocalGameSaveRecord({
    snapshot: createStartedLocalGameSnapshot(),
    savedAtIso: "2026-06-09T23:30:00.000Z",
  });

  assert.equal(await store.loadCurrent(), null);
  assert.deepEqual(await saveLocalGameSaveRecord(store, record), {
    state: "persisted",
  });

  const loaded = await store.loadCurrent();
  assert.deepEqual(loaded, record);

  assert.deepEqual(await clearLocalGameSaveRecord(store), {
    state: "cleared",
  });
  assert.equal(await store.loadCurrent(), null);
});

test("local game save records reject corrupt metadata and storage version mismatches", () => {
  const record = createStoredLocalGameSaveRecord({
    snapshot: createStartedLocalGameSnapshot(),
    savedAtIso: "2026-06-09T23:30:00.000Z",
  });

  assert.equal(assertStoredLocalGameSaveRecord(record), record);
  assert.throws(
    () => assertStoredLocalGameSaveRecord({ ...record, schemaVersion: 2 }),
    InvalidStoredLocalGameSaveRecordError,
  );
  assert.throws(
    () =>
      assertStoredLocalGameSaveRecord({
        ...record,
        dataSource: { ...record.dataSource, byteLength: 999 },
      }),
    InvalidStoredLocalGameSaveRecordError,
  );
});

test("local game save operation helpers return recoverable error states", async () => {
  const failingStore = {
    async loadCurrent() {
      return null;
    },
    async saveCurrent() {
      throw new Error("save quota exhausted");
    },
    async clearCurrent() {
      throw new Error("save delete denied");
    },
  };
  const record = createStoredLocalGameSaveRecord({
    snapshot: createStartedLocalGameSnapshot(),
  });

  assert.deepEqual(await saveLocalGameSaveRecord(failingStore, record), {
    state: "error",
    message: "save quota exhausted",
  });
  assert.deepEqual(await clearLocalGameSaveRecord(failingStore), {
    state: "error",
    message: "save delete denied",
  });
});
